// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeGuardian_API.Data;

#nullable disable

namespace TimeGuardian_API.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20230526102524_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TimeGuardian_API.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SessionTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 6339,
                            EndTime = new DateTime(2023, 5, 17, 18, 58, 13, 0, DateTimeKind.Unspecified),
                            SessionTypeId = 1,
                            StartTime = new DateTime(2023, 5, 17, 17, 12, 34, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Duration = 3600,
                            EndTime = new DateTime(2023, 5, 17, 19, 58, 13, 0, DateTimeKind.Unspecified),
                            SessionTypeId = 3,
                            StartTime = new DateTime(2023, 5, 17, 18, 58, 13, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Duration = 15787,
                            EndTime = new DateTime(2023, 5, 17, 23, 47, 3, 0, DateTimeKind.Unspecified),
                            SessionTypeId = 3,
                            StartTime = new DateTime(2023, 5, 17, 19, 23, 56, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Duration = 15787,
                            EndTime = new DateTime(2023, 5, 17, 23, 47, 3, 0, DateTimeKind.Unspecified),
                            SessionTypeId = 1,
                            StartTime = new DateTime(2023, 5, 17, 19, 23, 56, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TimeGuardian_API.Models.SessionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SessionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nauka"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Praca"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Prokrastynacja"
                        });
                });

            modelBuilder.Entity("TimeGuardian_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 26, 12, 25, 24, 521, DateTimeKind.Local).AddTicks(3530),
                            Email = "admin@admin.com",
                            Login = "Admin",
                            Password = "Admin1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 26, 12, 25, 24, 521, DateTimeKind.Local).AddTicks(3555),
                            Email = "jan@jan.com",
                            Login = "Jan",
                            Password = "Jan1"
                        });
                });

            modelBuilder.Entity("TimeGuardian_API.Models.Session", b =>
                {
                    b.HasOne("TimeGuardian_API.Models.SessionType", "SessionType")
                        .WithMany()
                        .HasForeignKey("SessionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeGuardian_API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionType");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
